/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AgeBand = "YOUNG_CHILD" | "PRETEEN" | "TEEN" | "OLDER_TEEN";
export type BasePolicy = {
  timezone: string;
  unknown_domain_policy: UnknownDomainPolicy;
  unknown_app_policy: UnknownAppPolicy;
  unknown_app_daily_minutes?: number;
  daily_device_budget_minutes?: number;
  hard_category_rules: CategoryRule[];
  default_category_rules: CategoryRule[];
  safety_allowlist: {
    target_kind: "APP" | "DOMAIN" | "CATEGORY";
    target_ref: string;
  }[];
};
export type UnknownDomainPolicy = "BLOCK" | "BLOCK_WHILE_CLASSIFYING" | "ALLOW_WHILE_CLASSIFYING" | "ALLOW_AND_NOTIFY";
export type UnknownAppPolicy = "BLOCK" | "LIMIT_AND_NOTIFY" | "ALLOW_AND_NOTIFY" | "ALLOW";
export type CategoryRule = {
  rule_id: string;
  category: Category;
  action: Action;
  daily_minutes?: number;
  schedule?: TimeWindow;
  exclude_from_budget?: boolean;
};
export type Category =
  | "ADULT_PORNOGRAPHY"
  | "SEXUAL_CONTENT"
  | "GAMBLING"
  | "DRUGS_CONTROLLED_SUBSTANCES"
  | "ALCOHOL_TOBACCO"
  | "GRAPHIC_VIOLENCE_GORE"
  | "SELF_HARM_SUICIDE"
  | "HATE_EXTREMISM"
  | "WEAPONS"
  | "MALWARE"
  | "PHISHING_SCAMS"
  | "ANONYMOUS_CHAT"
  | "DATING"
  | "PROXY_VPN_TOR"
  | "PIRACY"
  | "SOCIAL_MEDIA"
  | "STREAMING_VIDEO"
  | "GAMES"
  | "SHOPPING"
  | "AI_ASSISTANTS"
  | "EDUCATION"
  | "SEARCH_ENGINES"
  | "NEWS"
  | "MESSAGING"
  | "PRODUCTIVITY"
  | "UNKNOWN";
export type Action = "ALLOW" | "BLOCK" | "UNLIMITED" | "LIMIT" | "SCHEDULE" | "ASK_PARENT";
export type AppRule = {
  rule_id: string;
  app_ref: string;
  action: Action;
  daily_minutes?: number;
  schedule?: TimeWindow;
  exclude_from_budget?: boolean;
};
export type DomainRule = {
  rule_id: string;
  domain: string;
  match?: "EXACT" | "SUBDOMAINS";
  action: Action;
  daily_minutes?: number;
  schedule?: TimeWindow;
  exclude_from_budget?: boolean;
};
export type Routine = {
  routine_id: string;
  name: string;
  kind: "SCHEDULED" | "MANUAL";
  window?: TimeWindow;
  allowed_apps?: string[];
  allowed_categories?: Category[];
  blocked_apps?: string[];
  blocked_categories?: Category[];
  web_mode?: "BALANCED" | "STRICT";
  communication_mode?: "NORMAL" | "ESSENTIAL_ONLY";
};
export type TemporaryOverride = {
  rule_id: string;
  target_kind: "APP" | "DOMAIN" | "CATEGORY";
  target_ref: string;
  action: Action;
  daily_minutes?: number;
  starts_at: string;
  expires_at: string;
};

export interface SignedPolicyBundle {
  schema_version: 1;
  policy_version: number;
  family_id: string;
  child_profile_id: string;
  issued_at: string;
  expires_soft_at: string;
  key_id: string;
  age_band: AgeBand;
  base_policy: BasePolicy;
  app_rules: AppRule[];
  domain_rules: DomainRule[];
  category_rules: CategoryRule[];
  routines: Routine[];
  temporary_overrides: TemporaryOverride[];
  communication_safety: CommunicationSafety;
  signature: string;
}
export interface TimeWindow {
  /**
   * @minItems 1
   */
  days: [number, ...number[]];
  start: string;
  end: string;
}
export interface CommunicationSafety {
  enabled: boolean;
  severity_threshold: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  android_notification_signals: boolean;
  android_accessibility_signals: boolean;
}
