"""Generate the typed OpenAPI document consumed by workspace clients."""

import json
import os
import sys
from pathlib import Path

os.environ.setdefault("GUARDIAN_JWT_SECRET", "openapi-generation-secret-0123456789")
os.environ.setdefault("GUARDIAN_POLICY_PRIVATE_KEY", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")
sys.path.insert(0, str(Path(__file__).parents[1] / "backend"))

from app.api.app import app  # noqa: E402


output = Path(__file__).parents[1] / "packages" / "api-client" / "src" / "generated.ts"
schema = app.openapi()
document = json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False)
paths = sorted(schema.get("paths", {}))
path_union = " | ".join(json.dumps(path) for path in paths) or "never"
output.write_text(
    "// Generated by scripts/generate_openapi_client.py; do not edit manually.\n"
    f"export const openApiDocument = {document} as const;\n\n"
    f"export type GuardianApiPath = {path_union};\n\n"
    "export class GeneratedGuardianError extends Error {\n"
    "  constructor(message: string, readonly status: number) {\n"
    "    super(message);\n"
    "    this.name = \"GeneratedGuardianError\";\n"
    "  }\n"
    "}\n\n"
    "export class GeneratedGuardianClient {\n"
    "  constructor(\n"
    "    private readonly baseUrl: string,\n"
    "    private readonly getToken?: () => Promise<string | null>,\n"
    "  ) {}\n"
    "  async request<T>(path: GuardianApiPath, init: RequestInit = {}): Promise<T> {\n"
    "    const headers = new Headers(init.headers);\n"
    "    headers.set(\"Content-Type\", \"application/json\");\n"
    "    const token = await this.getToken?.();\n"
    "    if (token && !headers.has(\"Authorization\")) headers.set(\"Authorization\", `Bearer ${token}`);\n"
    "    const response = await fetch(`${this.baseUrl}${path}`, { ...init, headers });\n"
    "    if (!response.ok) {\n"
    "      const body = (await response.json().catch(() => ({}))) as { error?: { message?: string } };\n"
    "      throw new GeneratedGuardianError(body.error?.message ?? `Guardian API request failed: ${response.status}`, response.status);\n"
    "    }\n"
    "    if (response.status === 204) return undefined as T;\n"
    "    return (await response.json()) as T;\n"
    "  }\n"
    "}\n",
)
